import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useStoryblokState, getStoryblokApi, StoryblokComponent } from "@storyblok/react"
import FeaturedProducts from "../src/components/FeaturedProducts";
import Hero from "../src/components/Hero";
import { client } from "../utils/shopifyStore";

export default function Home(props) {
  let story = useStoryblokState(props.story);


  console.log(story);

  return (
    <div className={styles.container}>
      <Head>
        <title>Reduced Test Case</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header>
        <h1>
          { story ? story.name : 'My Site' }
        </h1>
      </header>

      <Hero />
      <FeaturedProducts products={props.products} />

      <StoryblokComponent blok={story.content} />
 
    </div>
  )
}

export async function getStaticProps() {
  // home is the default slug for the homepage in Storyblok
  let slug = "home";
 
  // load the draft version
  let sbParams = {
    version: "draft", // or 'published'
  };
 
  const storyblokApi = getStoryblokApi();
  let { data } = await storyblokApi.get(`cdn/stories/${slug}`, sbParams);

  const products = await client.product.fetchAll();
  // Fetch products
  const infos = await client.shop.fetchInfo();
  // Fetch shop Info if you think about SEO and title and ... to your page
  const policies = await client.shop.fetchPolicies();
  // fetch shop policy if you have any
 
  return {
    props: {
      story: data ? data.story : false,
      key: data ? data.story.id : false,
      infos: JSON.parse(JSON.stringify(infos)),
      policies: JSON.parse(JSON.stringify(policies)),
      products: JSON.parse(JSON.stringify(products)),
    },
    revalidate: 3600, // revalidate every hour
  };
}